CREATE TABLE DEPARTMENT (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(45) NOT NULL
);


CREATE TABLE COURSE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(45) NOT NULL,
    DEPARTMENT_ID BIGINT NOT NULL
);

CREATE TABLE STUDENT (
     ID BIGINT AUTO_INCREMENT PRIMARY KEY,
     FULLTIME TINYINT(1) NOT NULL,
     AGE INT NOT NULL,
     FIRSTNAME VARCHAR(45) NOT NULL,
     LASTNAME VARCHAR(45) NOT NULL
);


INSERT INTO DEPARTMENT VALUES (1,'DEC');
INSERT INTO COURSE VALUES (1,'MAS',1);
INSERT INTO COURSE VALUES (2,'SPT',1);
INSERT INTO COURSE VALUES (3, 'PST', 1);
INSERT INTO STUDENT VALUES (1,0,25,'Test','TestLN');
INSERT INTO STUDENT VALUES (2,1,28,'HA','MO');
INSERT INTO STUDENT VALUES (3,1,27,'fn','ln');
